### ISSUE TITLE
Please add CLIENT_ID to your .env error after setup

### ISSUE THREAD

**Issue by 0xbs0d** [aninternetof/rover-code#150]
I finished the setup, copied the env file to the root of the rovercode dir and I keep getting "Please add CLIENT_ID to your .env". Since that's the same error I was getting while i tried to start the service without the .env file the first time, I can only assume that it's not finding the .env file. What am I doing wrong?

**Comment by aninternetof** [comment]
Hi @immigrantsheep, thanks for reporting the issue!

You're right, it's possible that it's not finding the .env. Just to double check, the file is names `.env`, and it is saved at the root directory (next to the README.md)?

If that's all right, then could you confirm that the contents of the .env look something like this?
```
CLIENT_ID=XXXXXXXXXXXXXXXXX
CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXX
```
We had a problem a while back where the downloaded .env file had the wrong formatting in it. I thought it was fixed, but maybe there's still an issue!

**Comment by jeeshofone** [comment]
hey @immigrantsheep ! let me know if you keep hitting this snag and which branch you're working out of

**Comment by immigrantsheep** [comment]
Hey @aninternetof  sorry I couldn't get back to you sooner. The name of the file is rovercode_yourrovername.env and it's located in the root of the rovercode folder. I also checked the content of the file and it does have both CLIENT_ID and CLIENT_SECRET in it. 

@jeeshofone I cloned the master branch

I'm using ubuntu server 18.4 btw

**Comment by aninternetof** [comment]
Thanks @immigrantsheep!

If your file is named something like `rovercode_yourrovername.env`, then you'll want to rename it to only `.env` (nothing before the period). That will allow the service to find it.

Reading through our instructions, I see how that's confusing. I'll make a ticket to change the instructions to be more clear.

Let us know if renaming the file to only `.env` fixes the problem!

**Comment by aninternetof** [comment]
Horray! Feel free to let us know if you hit any other issues down the line.

**Comment by immigrantsheep** [comment]
Will do and thank you :)

**Comment by aninternetof** [comment]
Here is the new issue to make the docs more clear: https://github.com/rovercode/rovercode/issues/152
